### ISSUE TITLE
Andrew's Design Feedback 7/16/2021

### ISSUE THREAD

**Issue by phil-plencner-hl** [harvard-lts/drs-migration-dashboard#5]
- It looks like “Progress by bytes” should actually be “Progress by files”
- The order (from left to right) should either be from more granular to less granular (or the other way around). Granularity: bytes (i.e. filesize), files, objects

**Comment by mferrarini** [comment]
It occurred to me that the google sheet I created doesn’t include columns for “verified” and “verified failed”. 

I made new [V2 sheet](https://docs.google.com/spreadsheets/d/1FFv-csMLes-c6rQWCQBZa1PvrlY0b78XpQs8LpppUZA/edit#gid=457606513) to reflect this and updated the column headings so that they are 1) in order and 2) include correct titles (i.e. changing “Progress by bytes” to “Progress by files”). 

@awoods can you confirm that these titles makes sense now?

**Comment by awoods** [comment]
Column titles in V2 tab and order from most granular (bytes) to least granular (objects) is perfect.
